[build]
  publish = "dist"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_APP_ENV = "netlify"

[context.deploy-preview.environment]
  VITE_APP_ENV = "netlify"

[context.branch-deploy.environment]
  VITE_APP_ENV = "netlify"