[build]
  publish = "dist/public"
  command = "vite build --config vite.config.netlify-auth.ts"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_APP_ENV = "netlify"

[context.deploy-preview.environment]
  VITE_APP_ENV = "netlify"

[context.branch-deploy.environment]
  VITE_APP_ENV = "netlify"